#!/bin/sh

if pgrep -a -x picom | grep glx-fshader-win > /dev/null; then
	pkill -x picom
	sleep 0.1
	picom -b --experimental-backends
	toggle_mode="color"
else
	pkill -x picom
	sleep 0.1

	shader="uniform sampler2D tex;
		uniform float opacity;
		void main() {
			vec4 c = texture2D(tex, gl_TexCoord[0].xy);
			float y = dot(c.rgb, vec3(0.2126, 0.7152, 0.0722));
			gl_FragColor = opacity*vec4(y, y, y, c.a);
		}"

	picom -b --backend glx --glx-fshader-win "${shader}" 2> /dev/null
	toggle_mode="grayscale"
fi
